// Games list (alphabetical). Add a game: {id,t:title,u:url,a:x-handle}
const GAMES=[
{id:"g35",t:"Astra Dlicom",u:"https://astradlicom.netlify.app",a:"LuiseM2707"},
{id:"g27",t:"Bubble Dlic",u:"https://bubble-dlic.vercel.app",a:"teeenzyy"},
{id:"g10",t:"Clever Hotteok",u:"https://clever-hotteok-70af60.netlify.app",a:"NazibHa93298933"},
{id:"g28",t:"D Lost Post",u:"https://d-lost-post.vercel.app",a:"gioviiluxe"},
{id:"g47",t:"Dili Birds",u:"https://dili-birds.vercel.app",a:"ARIbnJahid1"},
{id:"g34",t:"Dili Cart",u:"https://dili-cart.pages.dev",a:"00xmado"},
{id:"g37",t:"Dili Defender",u:"https://dili-defender-browse-fwlo.bolt.host",a:"its_fayzal"},
{id:"g15",t:"Dili Delivery",u:"https://dili-delivery.vercel.app",a:"quangdai1721"},
{id:"g1",t:"Dili Fighter",u:"https://dilifighter.vercel.app",a:"BadhonAI"},
{id:"g6",t:"Dili Glitched Escape",u:"https://dili-glitched-escape.vercel.app",a:"attract_ga29482"},
{id:"g4",t:"Dili Jump",u:"https://dili-jump.vercel.app",a:"LevSageAI"},
{id:"g7",t:"Dili Jump Dlicom",u:"https://dilijumpdlicom.vercel.app",a:"Crypto_Atanu"},
{id:"g43",t:"Dili Maze",u:"https://d210000.github.io/DILIMAZE/",a:"donlyash"},
{id:"g41",t:"Dili Neon Run",u:"https://dili-neon-run.vercel.app",a:"Batman_1718R"},
{id:"g18",t:"Dili Orbit",u:"https://diliorbit.netlify.app/play",a:"notkiws"},
{id:"g17",t:"Dili Subway Surfers",u:"https://dili-subway-surfers3.vercel.app",a:"0x6Leo"},
{id:"g29",t:"Dili Surfer",u:"https://dili-surfer.vercel.app",a:"0xmisty_"},
{id:"g33",t:"Dli Merge",u:"https://dli-merge.netlify.app",a:"Diffinity9iig"},
{id:"g26",t:"Dli Miniworld",u:"https://dli-miniworld.vercel.app",a:"BrianSO7"},
{id:"g14",t:"Dli Run",u:"https://dlirun.vercel.app",a:"TarunDhal460957"},
{id:"g3",t:"Dlicom Academy Game",u:"https://dlicom-academy-game-t324.bolt.host",a:"armelkabore641"},
{id:"g52",t:"Dlicom Arena (Netlify)",u:"https://dlicom-arena.netlify.app",a:"absBogdan"},
{id:"g38",t:"Dlicom Arena (Render)",u:"https://dlicom-arena.onrender.com",a:"yournahian"},
{id:"g48",t:"Dlicom Arena (Vercel)",u:"https://dlicom-arena.vercel.app",a:"DARKSEID829909"},
{id:"g31",t:"Dlicom Arrow Jam",u:"https://dlicom-arrow-jam.vercel.app",a:"offloner"},
{id:"g40",t:"Dlicom Attack",u:"https://dlicom-attack.vercel.app",a:"Chaos_dev_"},
{id:"g9",t:"Dlicom Boomer",u:"https://dlicom-boomer-pa1z.vercel.app",a:"kieumanhquan"},
{id:"g42",t:"Dlicom Cyber Fantasy",u:"https://dlicom-cyber-fantasy.vercel.app",a:"Gift2207"},
{id:"g12",t:"Dlicom Dojo",u:"https://dlicom-dojo.vercel.app",a:"WebTigerX"},
{id:"g5",t:"Dlicom Dropzone",u:"https://dlicom-dropzone.onrender.com",a:"dezyyy_y"},
{id:"g46",t:"Dlicom Fantasy",u:"https://dlicomfantasy.netlify.app/play",a:"ToobywithhisX"},
{id:"g2",t:"Dlicom Games",u:"https://dlicomgames.flxthe6th.workers.dev",a:"armelkabore641"},
{id:"g51",t:"Dlicom Games (Flx)",u:"https://dlicomgames.flxthe6th.workers.dev",a:"flxthesixth"},
{id:"g11",t:"Dlicom Indie",u:"https://dlicom.indiedev.cloud",a:"humbleEnzo"},
{id:"g8",t:"Dlicom Neon Hunt",u:"https://dlicom-neon-hunt.netlify.app",a:"Bapparaj_fan"},
{id:"g49",t:"Dlicom Night Shift",u:"https://dlicomnightshift.vercel.app",a:"Virdzhi292"},
{id:"g21",t:"Dlicom Race",u:"https://dlicomrace.vercel.app",a:"Longlhu2Huu"},
{id:"g50",t:"Dlicom Runnn",u:"https://dlicomrunnnn.netlify.app",a:"ToobywithhisX"},
{id:"g19",t:"Dlicom Share HTML",u:"https://sharehtml.zhenjia.dev/v/65egN6Fhr5/",a:"Ruddro__islam02"},
{id:"g13",t:"Dlicom Slash",u:"https://jd-dlicom-slash.vercel.app",a:"DebnaJayan61106"},
{id:"g20",t:"Dlicom: Journey to DCO",u:"https://quytu9868.itch.io/dlicom-journey-to-dco",a:"QuyTu140498"},
{id:"g45",t:"Dlidla Maze Puzzle",u:"https://puzzle-dlidla-maze.vercel.app",a:"nekad95"},
{id:"g44",t:"Fishing Dlicom",u:"https://fishing-supdlicomcom.vercel.app",a:"anzyxZ"},
{id:"g22",t:"Flappy Dili",u:"https://flappy-dili.vercel.app",a:"Davevnvn"},
{id:"g39",t:"Hans Simiko",u:"https://hanssimiko.vercel.app",a:"0xHanssfzl"},
{id:"g53",t:"Last Message",u:"https://last-message-lac.vercel.app",a:"nxrskyaa"},
{id:"g16",t:"Lively Hotteok",u:"https://lively-hotteok-af103c.netlify.app",a:"blockzen_alpha"},
{id:"g25",t:"Luminous Kulfi",u:"https://luminous-kulfi-7a67a7.netlify.app",a:"ZisanBabu___"},
{id:"g32",t:"Pixels Saga Dlicom",u:"https://pixels-saga-dlicom.netlify.app",a:"javapee006"},
{id:"g36",t:"Retro Platformer",u:"https://retro-platformer-gam-61k7.bolt.host",a:"indra0_0x"},
{id:"g24",t:"Startling Rolypoly",u:"https://startling-rolypoly-fe41e8.netlify.app",a:"ItzXaimBro"},
{id:"g23",t:"TC Game",u:"https://tc-game-pub.vercel.app",a:"elneno13nhtw"},
{id:"g30",t:"Tyconn Cafe Dlicom",u:"https://tyconn-cafe-dlicom.vercel.app",a:"Donutloverv6"}
];
